In [3]:
pip install lxml

Collecting lxml
  Downloading lxml-5.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 64.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: lxml
Successfully installed lxml-5.1.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd 
import lxml

In [3]:
#Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.
data = [4,8,15,16,23,42]
my_series = pd.Series(data)
print(my_series)
type(my_series)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

pandas.core.series.Series

In [4]:
my_list = list(range(11))
my_series = pd.Series(my_list)
print(my_series)
type(my_series)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

pandas.core.series.Series

In [5]:
pd.DataFrame([['Name' , 'age' , 'gender'],
             ['Alice' , '25' , 'Female'],
             ['Bob' , '30' , 'Male'], 
             ['Claire' , '27', 'Female']])

        0    1       2
0    Name  age  gender
1   Alice   25  Female
2     Bob   30    Male
3  Claire   27  Female

In [6]:
#Q3. Create a Pandas DataFrame that contains the following data:
data = {'Name' : ['Alice' , '25' , 'Female'],
       'Age' : ['Bob' , '30' , 'Male'],
       'Gender':['Claire' , '27', 'Female']}
pd.DataFrame(data)

     Name   Age  Gender
0   Alice   Bob  Claire
1      25    30      27
2  Female  Male  Female

Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.

ans :- 

DataFrame:
    A DataFrame is a two-dimensional, labeled data structure in Pandas. It resembles a table with rows and columns.

    Key characteristics:
        Contains potentially different types of data in its columns.
        Supports both row and column labels.
        Can be thought of as a dictionary-like container for Series objects.
    Use cases:
    
        Handling structured data, such as CSV files, Excel spreadsheets, or database tables.
        Manipulating and analyzing tabular data.
        
Example of creating a DataFrame from a dictionary:

In [7]:
#Example:-
data = {'Name' : ['Alice' , '25' , 'Female'],
       'Age' : ['Bob' , '30' , 'Male'],
       'Gender':['Claire' , '27', 'Female']}
pd.DataFrame(data)

     Name   Age  Gender
0   Alice   Bob  Claire
1      25    30      27
2  Female  Male  Female

Series:

    A Series is a one-dimensional array-like data structure in Pandas. It represents a single column of data.
    
    Key characteristics:
        Contains homogeneous data (i.e., data of the same type) in a single column.
        Has an associated index (usually numeric or labeled).
        
    Use cases:
        Representing a single feature or variable.
        Extracting specific columns from a DataFrame.
        
        
Example of creating a Series from a list:

In [9]:
#Example:- 
data = [4,8,15,16,23,42]
my_series = pd.Series(data)
print(my_series)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [16]:
#Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can
#you give an example of when you might use one of these functions?

#solution:- 

#read_csv():

'''Loads data from a CSV file into a DataFrame.
Example: Loading data from a CSV file named "services.csv" '''
df = pd.read_csv("services.csv")
print(df)
#fillna():
'''Replaces missing (NaN) values in a DataFrame with specified values.
Example: Filling missing values with zeros:'''

df.fillna(0, inplace = True)
print(df)

#mean() and std() :- 
'''Calculate the mean and standard deviation of a Series or DataFrame.
Example: Calculating the average score in a student dataset:'''

ava_score = df['location_id'].mean()
std_score = df['location_id'].std()
print(ava_score)
print(std_score)

#columns()
''' When you call this .columns then you can see all noumber of columns '''
df.columns

#head()
''' this type of function works showing first 5 number of columns '''
df.head()

#tail()
'''this type of function works showing last 5 number of columns '''
df.tail()

    id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN
1    2            2         NaN                       NaN
2    3            3         NaN                       NaN
3    4            4         NaN                       NaN
4    5            5         NaN                       NaN
5    6            6         NaN                       NaN
6    7            7         NaN                       NaN
7    8            8         NaN                       NaN
8    9            9         NaN                       NaN
9   10           10         NaN                       NaN
10  11           11         NaN                       NaN
11  12           12         NaN                       NaN
12  13           13         NaN                       NaN
13  14           14         NaN                       NaN
14  15           15         NaN                       NaN
15  16           16         NaN                       NaN
16  17           17         NaN                       NaN
17  18           18         NaN                       NaN
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.
1                     NaN                 Apply by phone for an appointment.
2                     NaN        Phone for information (403-4300 Ext. 4322).
3                     NaN                                    Apply by phone.
4                     NaN                             Phone for information.
5                     NaN  Walk in or apply by phone for membership appli...
6                     NaN  Apply by phone or be referred by a doctor, soc...
7                     NaN                                    Apply by phone.
8                     NaN  Walk in. Proof of residency in California requ...
9                     NaN  Walk in. Proof of California residency to rece...
10                    NaN  Walk in. Proof of California residency require...
11                    NaN  Walk in or apply by phone, email or webpage re...
12                    NaN  Walk in. Proof of California residency require...
13                    NaN  Call for appointment. Referral from human serv...
14                    NaN          Walk in or through other agency referral.
15                    NaN  Walk in. Written application, identification r...
16                    NaN                              Call for information.
17                    NaN  Call for screening appointment. Medical visits...
18                    NaN     Call for screening appointment (650-347-3648).
19                    NaN                                           Walk in.
20                    NaN                    By phone during business hours.
21  Fotos para pasaportes                  Walk in or apply by phone or mail
22                    NaN                  Walk in or apply by phone or mail

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...
1        Residents of San Mateo County age 55 or over
2   Older adults age 55 or over who can benefit fr...
3   Parents, children, families with problems of c...
4   Low-income working families with children tran...
5                                             Any age
6   Older adults who have memory or sensory loss, ...
7   Senior citizens age 60 or over, disabled indiv...
8      Ethnic minorities, especially Spanish speaking
9                                                 NaN
10                                                NaN
11  Adults, parents, children in 1st-12th grades i...
12                                                NaN
13  Individuals or families with low or no income ...
14  Adult alcoholic/drug addictive men and women w...
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
0   A walk-in center for older adults that provide...
1   Provides training and job placement to eligibl...
2   Offers supportive counseling services to San M...
3   Provides supervised visitation services and a ...
4   Provides fixed 8% short term loans to eligible...
5   A multipurpose center offering a wide variety ...
6   Rosener House is a day center for older adults...
7   Delivers a hot meal to the home of persons age...
8   Provides general reading material, including b...
9   Provides general reading and media materials, ...
10  Provides general reading materials, including ...
11  Offers an intergenerational literacy program f...
12  Provides general reading materials, including ...
13  Provides food, clothing, bus tokens and shelte...
14  Provides a long-term (6-12 month) residential ...
15  Provides emergency assistance including food a...
16  Provides emergency food, clothing and furnitur...
17  By appointment only, Project Smile provides a ...
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                          eligibility                  email  \
0   Age 55 or over for most programs, age 60 or ov...                    NaN
1   Age 55 or over, county resident and willing an...                    NaN
2         Resident of San Mateo County age 55 or over                    NaN
3                                                None                    NaN
4   Eligibility: Low-income family with legal cust...                    NaN
5                                                None                    NaN
6                                      Age 18 or over                    NaN
7             Homebound person unable to cook or shop                    NaN
8     Resident of California to obtain a library card                    NaN
9             Resident of California to obtain a card                    NaN
10  Resident of California to obtain a library car...                    NaN
11  English-speaking adult reading at or below 7th...                    NaN
12    Resident of California to obtain a library card                    NaN
13  None for most services. For emergency assistan...                    NaN
14  Age 21-60, detoxed, physically able and willin...                    NaN
15                      None for emergency assistance                    NaN
16                                Low-income families                    NaN
17    Low-income person without access to health care                    NaN
18    Low-income person without access to health care                    NaN
19                                                NaN                    NaN
20                                                NaN                    NaN
21                                               None  passports@example.org
22                                               None                    NaN

    ...                            interpretation_services  \
0   ...                                                NaN
1   ...                                                NaN
2   ...                                                NaN
3   ...                                                NaN
4   ...                                                NaN
5   ...                                                NaN
6   ...                                                NaN
7   ...                                                NaN
8   ...                                                NaN
9   ...                                                NaN
10  ...                                                NaN
11  ...                                                NaN
12  ...                                                NaN
13  ...                                                NaN
14  ...                                                NaN
15  ...                                                NaN
16  ...                                                NaN
17  ...                                                NaN
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN
2   Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN
4      COMMUNITY SERVICES, Speakers, Automobile Loans       NaN
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
8   EDUCATION SERVICES, Library, Libraries, Public...       NaN
9   EDUCATION SERVICES, Library, Libraries, Public...       NaN
10  EDUCATION SERVICES, Library, Libraries, Public...       NaN
11  EDUCATION SERVICES, Adult, Alternative, Litera...       NaN
12  EDUCATION SERVICES, Library, Libraries, Public...       NaN
13  COMMUNITY SERVICES, Interpretation/Translation...       NaN
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...       NaN
15  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
16  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
17  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                                    name  \
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

                          required_documents  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  Government-issued picture identification
22                                       NaN

                            service_areas    status  \
0                                   Colma    active
1                        San Mateo County    active
2                        San Mateo County    active
3                        San Mateo County    active
4                        San Mateo County    active
5                        San Mateo County    active
6     Belmont, Burlingame, East Palo Alto    active
7                 Belmont, East Palo Alto    active
8                        San Mateo County    active
9                        San Mateo County    active
10                       San Mateo County    active
11                              Daly City    active
12                       San Mateo County    active
13    Belmont, Burlingame, East Palo Alto    active
14       Alameda County, San Mateo County    active
15                                    NaN    active
16  Colma, Daly City, South San Francisco    active
17                         East Palo Alto    active
18                    Belmont, Burlingame    active
19                                    NaN   defunct
20                       San Mateo County  inactive
21       Alameda County, San Mateo County    active
22       San Mateo County, Alameda County    active

                                            wait_time                 website  \
0                                            No wait.                     NaN
1                                             Varies.                     NaN
2                                             Varies.                     NaN
3                                            No wait.                     NaN
4                                                 NaN                     NaN
5                                            No wait.                     NaN
6                                            No wait.                     NaN
7                                            No wait.                     NaN
8                                            No wait.                     NaN
9                                            No wait.                     NaN
10                                           No wait.                     NaN
11  Depends on availability of tutors for small gr...                     NaN
12                                           No wait.                     NaN
13                                  Up to 20 minutes.                     NaN
14  Varies according to available beds for men and...                     NaN
15                                           No wait.                     NaN
16                                                NaN                     NaN
17                                            Varies.                     NaN
18                                            Varies.                     NaN
19                                                NaN                     NaN
20                                                NaN                     NaN
21                                No wait to 2 weeks.  http://www.example.com
22                                 No wait to 2 weeks  http://www.example.com

                                taxonomy_ids
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  105, 108, 108-05, 108-05-01, 111, 111-05
22                                       NaN

[23 rows x 22 columns]
    id  location_id  program_id         accepted_payments  \
0    1            1         0.0                         0
1    2            2         0.0                         0
2    3            3         0.0                         0
3    4            4         0.0                         0
4    5            5         0.0                         0
5    6            6         0.0                         0
6    7            7         0.0                         0
7    8            8         0.0                         0
8    9            9         0.0                         0
9   10           10         0.0                         0
10  11           11         0.0                         0
11  12           12         0.0                         0
12  13           13         0.0                         0
13  14           14         0.0                         0
14  15           15         0.0                         0
15  16           16         0.0                         0
16  17           17         0.0                         0
17  18           18         0.0                         0
18  19           19         0.0                         0
19  20           20         0.0                         0
20  21           21         0.0                         0
21  22           22         0.0  Cash, Check, Credit Card
22  23           22         0.0                         0

           alternate_name                                application_process  \
0                       0                         Walk in or apply by phone.
1                       0                 Apply by phone for an appointment.
2                       0        Phone for information (403-4300 Ext. 4322).
3                       0                                    Apply by phone.
4                       0                             Phone for information.
5                       0  Walk in or apply by phone for membership appli...
6                       0  Apply by phone or be referred by a doctor, soc...
7                       0                                    Apply by phone.
8                       0  Walk in. Proof of residency in California requ...
9                       0  Walk in. Proof of California residency to rece...
10                      0  Walk in. Proof of California residency require...
11                      0  Walk in or apply by phone, email or webpage re...
12                      0  Walk in. Proof of California residency require...
13                      0  Call for appointment. Referral from human serv...
14                      0          Walk in or through other agency referral.
15                      0  Walk in. Written application, identification r...
16                      0                              Call for information.
17                      0  Call for screening appointment. Medical visits...
18                      0     Call for screening appointment (650-347-3648).
19                      0                                           Walk in.

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,0.0,0,0,Call for screening appointment (650-347-3648).,0,Provides free medical and dental care to those...,Low-income person without access to health care,0,...,0,"HEALTH SERVICES, Outpatient Care, Community Cl...",0,San Mateo Free Medical Clinic,0,"Belmont, Burlingame",active,Varies.,0,0
19,20,20,0.0,0,0,Walk in.,0,no unrequired fields for this service,0,0,...,0,0,0,Service with blank fields,0,0,defunct,0,0,0
20,21,21,0.0,0,0,By phone during business hours.,0,just a test service,0,0,...,0,0,0,Service for Admin Test Location,0,San Mateo County,inactive,0,0,0
21,22,22,0.0,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,0.0,0,0,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,0,...,0,"Ruby on Rails/Postgres/Redis, testing, wic",0,Example Service Name,0,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,0

Q6. Which of the following is mutable in nature Series, DataFrame, Panel?

    Among the given options, DataFrame is mutable in nature. A DataFrame allows modifications to its contents, such as adding or removing columns, changing values, and reordering rows. On the other hand, a Series (which represents a single column) is also mutable, but a Panel (which is a three-dimensional data structure) has been deprecated in recent versions of Pandas and is no longer commonly used. Therefore, the correct answer is DataFrame.

Q7. Create a DataFrame using multiple Series. Explain with an example.  
    
    
    Let’s create a Pandas DataFrame using multiple Series. A DataFrame is a two-dimensional data structure that can hold heterogeneous data, and a Series is a one-dimensional labeled array. When we combine multiple Series, we create a DataFrame with each Series representing a column.

    Here’s an example:

        Suppose we have the following three Series:

        courses: A Series containing course names.
        fees: A Series containing corresponding course fees.
        discount: A Series containing discount amounts for each course.
        
        
We want to create a DataFrame where each course name, fee, and discount are in separate columns.

In [5]:
#example : - 
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name="courses")
fees = pd.Series([22000, 25000, 23000], name="fees")
discount = pd.Series([1000, 2300, 1000], name="discount")

df1 = pd.DataFrame([courses,fess,discount], axis = 1)
print(df)